// Code generated by "stringer -type=TokenSubtype"; DO NOT EDIT.

package jack_tokenizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN - -1]
	_ = x[NONE-1]
	_ = x[KW_CLASS-2]
	_ = x[KW_CONSTRUCTOR-3]
	_ = x[KW_FUNCTION-4]
	_ = x[KW_METHOD-5]
	_ = x[KW_FIELD-6]
	_ = x[KW_STATIC-7]
	_ = x[KW_VAR-8]
	_ = x[KW_INT-9]
	_ = x[KW_CHAR-10]
	_ = x[KW_BOOLEAN-11]
	_ = x[KW_VOID-12]
	_ = x[KW_TRUE-13]
	_ = x[KW_FALSE-14]
	_ = x[KW_NULL-15]
	_ = x[KW_THIS-16]
	_ = x[KW_LET-17]
	_ = x[KW_DO-18]
	_ = x[KW_IF-19]
	_ = x[KW_ELSE-20]
	_ = x[KW_WHILE-21]
	_ = x[KW_RETURN-22]
	_ = x[SYM_LEFT_BRACE-23]
	_ = x[SYM_RIGHT_BRACE-24]
	_ = x[SYM_LEFT_PAREN-25]
	_ = x[SYM_RIGHT_PAREN-26]
	_ = x[SYM_LEFT_BRACK-27]
	_ = x[SYM_RIGHT_BRACK-28]
	_ = x[SYM_PERIOD-29]
	_ = x[SYM_COMMA-30]
	_ = x[SYM_SEMICOLON-31]
	_ = x[SYM_PLUS-32]
	_ = x[SYM_MINUS-33]
	_ = x[SYM_ASTERISK-34]
	_ = x[SYM_SLASH-35]
	_ = x[SYM_AMPERSAND-36]
	_ = x[SYM_PIPE-37]
	_ = x[SYM_LESS_THAN-38]
	_ = x[SYM_GREATER_THAN-39]
	_ = x[SYM_EQUALS-40]
	_ = x[SYM_TILDE-41]
}

const (
	_TokenSubtype_name_0 = "UNKNOWN"
	_TokenSubtype_name_1 = "NONEKW_CLASSKW_CONSTRUCTORKW_FUNCTIONKW_METHODKW_FIELDKW_STATICKW_VARKW_INTKW_CHARKW_BOOLEANKW_VOIDKW_TRUEKW_FALSEKW_NULLKW_THISKW_LETKW_DOKW_IFKW_ELSEKW_WHILEKW_RETURNSYM_LEFT_BRACESYM_RIGHT_BRACESYM_LEFT_PARENSYM_RIGHT_PARENSYM_LEFT_BRACKSYM_RIGHT_BRACKSYM_PERIODSYM_COMMASYM_SEMICOLONSYM_PLUSSYM_MINUSSYM_ASTERISKSYM_SLASHSYM_AMPERSANDSYM_PIPESYM_LESS_THANSYM_GREATER_THANSYM_EQUALSSYM_TILDE"
)

var (
	_TokenSubtype_index_1 = [...]uint16{0, 4, 12, 26, 37, 46, 54, 63, 69, 75, 82, 92, 99, 106, 114, 121, 128, 134, 139, 144, 151, 159, 168, 182, 197, 211, 226, 240, 255, 265, 274, 287, 295, 304, 316, 325, 338, 346, 359, 375, 385, 394}
)

func (i TokenSubtype) String() string {
	switch {
	case i == -1:
		return _TokenSubtype_name_0
	case 1 <= i && i <= 41:
		i -= 1
		return _TokenSubtype_name_1[_TokenSubtype_index_1[i]:_TokenSubtype_index_1[i+1]]
	default:
		return "TokenSubtype(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
