// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package jack_tokenizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KEYWORD-0]
	_ = x[SYMBOL-1]
	_ = x[INT_CONSTANT-2]
	_ = x[STRING_CONSTANT-3]
	_ = x[IDENTIFIER-4]
}

const _TokenType_name = "KEYWORDSYMBOLINT_CONSTANTSTRING_CONSTANTIDENTIFIER"

var _TokenType_index = [...]uint8{0, 7, 13, 25, 40, 50}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
